### ISSUE TITLE
Uncaught AssertionError: The expression evaluated to a falsy value:  (0, _assert.default)(dockP...

### ISSUE THREAD

**Issue by CapitalSins** [atom-community/atom-ide-debugger#18]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Uncaught AssertionError: The expression evaluated to a falsy value:

  (0, _assert.default)(dockPane.element != null)

```
At assert.js:362

AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)(dockPane.element != null)

    at DebuggerLayoutManager._overridePaneInitialHeight (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:113:25)
    at Object.onPaneResize (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:149:14)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:354:24
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at Pane.setFlexScale (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:454850)
    at Pane.split (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:466051)
    at Pane.splitDown (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:465756)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:325:20)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:632:14
    at Array.forEach (<anonymous>)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:606:181)
    at DebuggerLayoutManager.showHiddenDebuggerPane (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:238:10)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:88:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:350382)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:684525)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:856521)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:854463)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:853453)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:857541)
```

### Commands

```
     -2:59.1.0 debugger:toggle-breakpoint (div.highlights)
     -2:49.2.0 pane:split-up-and-copy-active-item (div#linter-panel.)
     -2:47 pane:split-down-and-copy-active-item (div.item-views)
     -2:44.9.0 pane:split-up-and-copy-active-item (div#linter-panel.)
  3x -2:34.4.0 pane:close (div.item-views)
     -2:13.4.0 command-palette:toggle (input.hidden-input)
  2x -2:08.8.0 core:move-down (input.hidden-input)
     -2:07.2.0 core:confirm (input.hidden-input)
     -2:07.2.0 debugger:run-to-location (input.hidden-input)
  4x -1:55.8.0 debugger:toggle-breakpoint (div.highlights)
     -1:45.6.0 command-palette:toggle (input.hidden-input)
     -1:40.2.0 core:backspace (input.hidden-input)
     -1:35.4.0 debugger:show-window-Debugger (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-base 2.3.5 
atom-ide-console 0.0.2 
atom-ide-datatip 0.24.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.9 
atom-ide-markdown-service 2.0.0 
atom-ide-outline 2.0.0 
atom-ide-signature-help 0.15.3 
atom-material-syntax 1.0.8 
busy-signal 2.0.1 
ide-python 1.7.4 
linter 3.3.0 
linter-ui-default 3.3.0 
run 0.0.1 
teletype 0.13.4 
```

**Comment by momcilo78** [comment]
Same issue here + the following also gets triggered at the same time:
https://github.com/atom-community/ide-python/issues/284
