### ISSUE TITLE
Uncaught TypeError: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by Jose-Escamilla** [atom-community/atom-ide-debugger#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'current' of undefined

```
At C:\Users\jose0\.atom\packages\atom-ide-debugger\node_modules\react-dom\cjs\react-dom.production.min.js:250

TypeError: Cannot read property 'current' of undefined
    at Pj (/packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:250:24)
    at Tj (/packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:250:104)
    at Lj (/packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)
    at Jg (/packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:237:175)
    at lk (/packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:285:27)
    at tk (/packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:289:150)
    at /packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:296:204
    at Xj (/packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:244:244)
    at Object.exports.unmountComponentAtNode (/packages/atom-ide-debugger/node_modules/react-dom/cjs/react-dom.production.min.js:296:190)
    at HTMLElement.disconnectedCallback (/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:75:23)
    at HTMLElement.itemRemoved (/app.asar/src/pane-element.js:190:20)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1182710)
    at Emitter.emit (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1184151)
    at Pane.removeItem (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:462665)
    at Pane.destroyItem (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:463890)
```

### Commands

```
  2x -8:22.5.0 debugger:toggle (input.hidden-input)
     -8:04.9.0 core:paste (input.hidden-input)
  8x -8:03.2.0 core:backspace (input.hidden-input)
     -2:46.5.0 debugger:toggle (input.hidden-input)
     -2:46.5.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:14.5.0 debugger:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:14.5.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-ide-debugger 0.0.3 
atom-python-run 0.9.7 
autocomplete-python 1.17.0 
busy-signal 2.0.1 
minimap 4.39.12 
script 3.31.1 
```

**Comment by ThatXliner** [comment]
Does this reproduce on the latest version?
