### ISSUE TITLE
Uncaught TypeError: call.getFileName is not a function

### ISSUE THREAD

**Issue by jonodhawkins** [atom-community/atom-ide-debugger#23]
1. CTRL+SHIFT+P -> Debugger: Show Window Debugger

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Uncaught TypeError: call.getFileName is not a function

```
At assert.js:270

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:270:25)
    at innerOk (assert.js:361:17)
    at ok (assert.js:381:3)
    at DebuggerLayoutManager._overridePaneInitialHeight (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:113:25)
    at Object.onPaneResize (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:149:14)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:354:24
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at Pane.setFlexScale (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:456811)
    at Pane.split (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:468012)
    at Pane.splitDown (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:467717)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:325:20)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:632:14
    at Array.forEach (<anonymous>)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:606:181)
    at DebuggerLayoutManager.showHiddenDebuggerPane (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:238:10)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:88:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:352215)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:686807)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:555627)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:550506)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:352215)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1226991)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1223125)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:286551)
```

### Commands

```
     -0:13.3.0 command-palette:toggle (input.hidden-input)
     -0:10.4.0 core:backspace (input.hidden-input)
     -0:09.6.0 core:confirm (input.hidden-input)
     -0:09.5.0 debugger:show-window-Debugger (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-base 2.6.0 
atom-ide-console 0.0.2 
atom-ide-datatip 0.24.1 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.10 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.15.3 
busy-signal 2.0.1 
git-plus 8.7.1 
ide-python 1.8.0 
intentions 1.1.5 
language-batchfile 0.7.7 
language-latex 1.2.0 
language-matlab 0.2.1 
language-vb 0.1.0-pre1 
language-vba 0.2.5 
latex 0.50.2 
less-autocompile 1.0.0 
linter 3.3.1 
linter-python 3.1.2 
linter-ui-default 3.3.1 
markdown-to-html 0.5.0 
markdown-to-pdf 0.1.1 
pdf-view 0.73.0 
php-twig 4.0.0 
pigments 0.40.6 
sass-autocompile 0.13.5 
script 3.32.2 
uikit-atom 0.3.2 
x-terminal 13.0.8 
```

**Comment by GrishaKirilin** [comment]
I have the same issue on Ubuntu.

1. CTRL+SHIFT+P -> Debugger: Show

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.2
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3


### Stack Trace

Uncaught TypeError: call.getFileName is not a function

```
At assert.js:270

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:270:25)
    at innerOk (assert.js:361:17)
    at ok (assert.js:381:3)
    at DebuggerLayoutManager._overridePaneInitialHeight (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:113:25)
    at Object.onPaneResize (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:149:14)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:354:24
    at Function.simpleDispatch (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:1187631)
    at Pane.setFlexScale (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:456811)
    at Pane.split (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:468012)
    at Pane.splitDown (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:467717)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:325:20)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:632:14
    at Array.forEach (<anonymous>)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:606:181)
    at /packages/atom-ide-debugger/dist/main.js:412:24)
    at CommandRegistry.handleCommandEvent (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:352215)
    at Object.didConfirmSelection (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:686807)
    at SelectListView.confirmSelection (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:14:555627)
    at HTMLDivElement.core:confirm (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:14:550506)
    at CommandRegistry.handleCommandEvent (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:352215)
    at KeymapManager.dispatchCommandEvent (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:1226991)
    at KeymapManager.handleKeyboardEvent (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:1223125)
    at WindowEventHandler.handleDocumentKeyEvent (/snap/atom/282/usr/share/atom/resources/app/static/<embedded>:11:286551)
```

### Commands

```
     -0:57.7.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:57.4.0 core:backspace (input.hidden-input)
     -0:54 editor:select-to-first-character-of-line (input.hidden-input)
     -0:53.7.0 core:backspace (input.hidden-input)
     -0:51.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:49.9.0 core:backspace (input.hidden-input)
  3x -0:47.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:35.7.0 core:save (input.hidden-input)
     -0:34.3.0 core:move-up (input.hidden-input)
     -0:34 datatip:toggle (input.hidden-input)
     -0:33.9.0 atom-beautify:beautify-editor (input.hidden-input)
     -0:33.6.0 core:save (input.hidden-input)
     -0:29.9.0 command-palette:toggle (input.hidden-input)
  5x -0:26.6.0 core:move-down (input.hidden-input)
     -0:25.5.0 core:confirm (input.hidden-input)
     -0:25.5.0 debugger:show (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.2.0 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-ide-base 2.6.0 
atom-ide-datatip 0.25.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.10 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.16.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-typescript 14.3.1 
autocomplete-clang 0.13.1 
autocomplete-cmake 0.3.1 
autocomplete-paths 2.15.2 
build-cmake 0.12.0 
busy-signal 2.0.1 
choose-pane 0.8.0 
clang-format 2.0.8 
CPP-Competitive-Programming-Snippets 1.0.1 
cpp-generator 1.0.1 
dark-one-dark-syntax 2.3.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
easy-motion-redux 1.3.3 
file-icons 2.1.47 
firacode 0.3.0 
git-time-machine 2.1.0 
gitkraken-glo 1.0.2 
hey-pane 1.2.0 
Hydrogen 2.16.3 
hydrogen-cell-separator 0.4.1 
ide-ccls 0.3.0 
ide-python 1.9.1 
intentions 1.1.5 
javascript-drag-import 0.1.13 
language-batch 0.4.0 
language-cmake 1.2.0 
language-cpp14 0.6.2 
language-cuda 0.1.0 
language-jenkinsfile 0.1.1 
language-restructuredtext 1.1.2 
language-viml 1.2.3 
language-x86-64-assembly 2.3.0 
linter 3.3.1 
linter-clang 4.1.2 
linter-clang-tidy 0.2.0 
linter-cppcheck 0.2.3 
linter-cpplint 2.1.0 
linter-eslint 8.6.6 
linter-shellcheck 1.6.0 
linter-spell-rst 0.4.0 
linter-ui-default 3.3.1 
minimap 4.39.14 
minimap-hide 0.3.0 
move-tab-or-split 1.1.1 
multi-wrap-guide 1.1.11 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
one-dark-vivid-syntax 1.8.1 
pane-layout-plus 0.7.4 
pane-move-plus 0.4.0 
platformio-ide-terminal 2.10.1 
pristine-ui 1.1.11 
rst-preview-pandoc 0.1.12 
rst-snippets 1.1.5 
split-diff 1.6.1 
sync-settings 5.2.11 
todo-show 2.3.2 
```

**Comment by BuZZ-dEE** [comment]
https://github.com/atom-community/atom-ide-debugger/issues/24
