### ISSUE TITLE
Uncaught TypeError: call.getFileName is not a function

### ISSUE THREAD

**Issue by BuZZ-dEE** [atom-community/atom-ide-debugger#25]
[Enter steps to reproduce:]

1. Just tried to show the debugger
2. Then I got this exception

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: "Arch Linux"
**Thrown From**: [atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger) package 0.0.3

### Stack Trace

Uncaught TypeError: call.getFileName is not a function

```
At assert.js:270

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:270:25)
    at innerOk (assert.js:361:17)
    at ok (assert.js:381:3)
    at DebuggerLayoutManager._overridePaneInitialHeight (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:113:25)
    at Object.onPaneResize (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:149:14)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:354:24
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Pane.setFlexScale (/usr/lib/atom/src/pane.js:170:18)
    at Pane.split (/usr/lib/atom/src/pane.js:1221:12)
    at Pane.splitDown (/usr/lib/atom/src/pane.js:1199:17)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:325:20)
    at /packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:632:14
    at Array.forEach (<anonymous>)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:606:181)
    at /packages/atom-ide-debugger/dist/main.js:412:24)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:405:43)
    at Object.didConfirmSelection (/usr/lib/atom/node_modules/command-palette/lib/command-palette-view.js:152:29)
    at SelectListView.confirmSelection (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at HTMLDivElement.core:confirm (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:105:14)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:405:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:153:34)
```

### Commands

```
     -0:07.6.0 intentions:highlight (input.hidden-input)
     -0:07.0 command-palette:toggle (input.hidden-input)
     -0:04.8.0 core:move-down (input.hidden-input)
     -0:04.5.0 core:confirm (input.hidden-input)
     -0:04.5.0 debugger:show (input.hidden-input)
```

### Non-Core Packages

```
angular-snippets 10.0.3 
atom-beautify 0.33.4 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-console 0.0.2 
atom-ide-datatip 0.25.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.1.0 
atom-ide-signature-help 0.16.0 
atom-inline-blame 0.0.10 
atom-typescript 14.3.2 
busy-signal 2.0.1 
css-hyperclick 0.1.5 
cursor-history 0.14.0 
declarations 1.1.3 
declarations-js 1.0.2 
docblockr 0.14.2 
editorconfig 2.6.1 
emmet 2.4.3 
find-selection 0.16.0 
git-plus 8.7.1 
git-time-machine 2.1.0 
highlight-line 0.12.0 
highlight-selected 0.17.0 
hyperclick 0.1.5 
ide-bash 1.0.11 
ide-css 0.4.0 
ide-html 0.7.0 
ide-java 0.9.1 
ide-json 0.2.1 
ide-python 1.9.4 
ide-typescript 0.9.2 
intentions 2.1.1 
js-hyperclick 1.13.3 
js-refactor 0.8.1 
jumpy 5.0.2 
language-freemarker 0.2.0 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-ini 1.25.0 
language-svg 0.9.2 
last-cursor-position 1.2.0 
linter 3.4.0 
linter-ui-default 3.4.1 
minimap 4.40.0 
open-file-in 1.2.3 
pigments 0.40.6 
prettier-atom 0.60.1 
project-manager 3.3.8 
refactor 0.11.5 
split-diff 1.6.1 
svg-preview 0.14.0 
svn 0.0.14 
teletype 0.13.4 
terminal-tab 0.6.0 
```

**Comment by BuZZ-dEE** [comment]
https://github.com/atom-community/atom-ide-debugger/issues/23
